Biblioteca NumPY - sigla np

In [ ]:
# Depois de importar a biblioteca uma primeira vez para o notebook n é preciso voltar a importar

In [3]:
import numpy as np

#Cria uma matriz com 3 elementos

a = np.array([1,"r",3])

ModuleNotFoundError: No module named 'numpy'

In [ ]:
# Tipo variável a

print(type(a))

<class 'numpy.ndarray'>


In [ ]:
# imprime o formato da variável. 3 linhas e nenhuma coluna.(linhas,colunas)
print(a.shape)

(3,)


In [ ]:
# Imprime os valores

print(a[0], a[1], a[2])

1 r 3


In [ ]:
# Altera o valor de um elemento da matriz

a[0] = 5

print(a)

['5' 'r' '3']


In [ ]:
# Cria uma matriz bidimensional

b = np.array([[1,2,3],[4,5,6]])

In [ ]:
# Imprime o formato da variável
print(b.shape)

(2, 3)


In [ ]:
#Imprime os valores
print(b[0,0], b[0,1], b[0,2], b[1,0], b[1,1], b[1,2])

1 2 3 4 5 6


In [ ]:
# Imprime todos os valores vetor unidimensional

for i in a:
    print(i)

5
r
3


In [ ]:
# Imprime todos os valores vetor multidimensional

for linha in b:
    print(linha)

[1 2 3]
[4 5 6]


In [ ]:
# Numeros de linhas e colunas

num_linhas, num_colunas = b.shape

(3,)

In [ ]:
#matrizes unidimensionais sao sempre linhas em python

In [ ]:
# Imprimir cada um dos elementos automaticamente

for i in range(0,num_linhas):
    for j in range(0,num_colunas):
        print("Posiçoes vector:", i, j, "Valor:", b[i][j])

TypeError: 'tuple' object cannot be interpreted as an integer

Tipos de dados
No numpy todos os elementos de uma matriz/ndarray são de um determinado tipo de dados.

In [ ]:
x = np.array([1.0, 2.0])
print(x.dtype)

float64


In [ ]:
x = np.array([1,2], dtype=np.float64)
print(x.dtype)

float64


Criação de matrizes/ndarray

A biblioteca NumPy fornece muitas formas de criar matrizes/ndarray.

In [ ]:
# Vetor de 5 elementos seguidos

print(np.arange(5))

[0 1 2 3 4]


In [ ]:
# Vetor de 5 elementos (igualmente espaçados), entre 1 e 2, dividido em 5 partes. pode andar para tras ou para a frente, negativos etc

print(np.linspace(1,2,5))

[1.   1.25 1.5  1.75 2.  ]


In [ ]:
#Vetor de 5 elementos iguais a 0s

print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [ ]:
# Matriz 2x2 de zeros

print(np.zeros((5,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Matriz 2x3 de 1´s

print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Matriz 4x2 de setes(7)
print(np.full((4,2),7))

[[7 7]
 [7 7]
 [7 7]
 [7 7]]


In [ ]:
# Matriz identidade 2x2. matriz em que os 1´s ficam na diagonal

print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Criação de vetores de diferentes dimensões


In [ ]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3,], [4,5,6], [1,2,3], [4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)



0
1
2
3


Criação matrizes com valores aleatorios

O NumPy permite a criação de matrizes com valores aleatorios que podem seguir uma das muitas distribuições disponiveis no NumPy(bet, binomial, qui-quadrado...)

exemplos

In [ ]:
# Geração de uma matriz/ndarray(3*5) com valores aleatorios com base na
# distribuição uniforme com valores entre [0,1]

e = np.random.random((3,5))
print ("matriz de valores aleatorios entrre 0 e 1, com base numa distribuição uniforme")
print(e)

matriz de valores aleatorios entrre 0 e 1, com base numa distribuição uniforme
[[0.19566264 0.30137681 0.94350601 0.48591091 0.6079489 ]
 [0.80655541 0.28613394 0.74063533 0.87020334 0.54894314]
 [0.38027865 0.02467682 0.9628729  0.67889958 0.55054989]]


In [ ]:
# Para verificar pode-se calcular a média e o desvio padrao dos valores

print("Média (a+b)/2, em que a = 0 e b = 1: " + str(np.mean(e)))
print("Desvio padrão(Raiz Quadrada((b-a)^2/12)): " + str(np.std(e)))
print()      

SyntaxError: invalid syntax (2387524297.py, line 4)

In [ ]:
#Geração de uma matriz/ndarray(3*5) com valores aleatorios com base 
# na distribuição normal com  media 0 e desvio padrao 1
# o primeiro parametro é media, o segundo o desvio padrao e o terceiro a matriz

f = np.random.normal(0,1,(3,5))
print("Matriz de valores aleatorios entre 0 e 1, com base numa distribuição normal")
print(f)

Matriz de valores aleatorios entre 0 e 1, com base numa distribuição normal
[[-0.83070543 -0.67820087  0.93484858  1.07742949  1.54236681]
 [-0.05758711  0.04803822  0.07046872  0.32434101 -0.10132927]
 [ 0.1135524  -0.6230589  -1.70855875 -1.2786591   0.23942863]]


In [ ]:
# para verificar e calcular a media e o desvio padrao dos valores

print("Média(0) " + str(np.mean(f)))
print("Desvio Padrão (1): " + str(np.std(f)))
print("Nota: com poucos calores é provável que a media e o desvio padrao nao sejam 0 e 1, Correr para uma matriz de maiores dimensões")
print()


Média(0) -0.06184170516781303
Desvio Padrão (1): 0.8424160783917075
Nota: com poucos calores é provável que a media e o desvio padrao nao sejam 0 e 1, Correr para uma matriz de maiores dimensões



In [ ]:
# Geração de uma matriz/ndarray (3x5) com valores aleatorios com base na
# distribuição exponencial. O primeiro padrao é a escala
# (inverso da taxa, escala = 1/lambda) e o segundo a matriz lambda1 = 5

lambda1 = 5

g = np.random.exponential(1/lambda1,(3,5))
print("Matriz de valores aleatorios entre 0,1 com base numa distribuição exponencial")
print(g)

Matriz de valores aleatorios entre 0,1 com base numa distribuição exponencial
[[0.1057099  0.00484197 0.10943402 0.00685898 0.05702682]
 [0.02745974 0.37446266 0.00536593 0.16260388 0.76718098]
 [0.0932474  0.14374759 0.16811925 0.00999024 0.00603535]]


In [ ]:
# Para verificar que esta certo pode se calcular a media e a variancia dos valores
#print ("lambda:  + str(lambda1))
print("Média (1/lambda): " + str(np.mean(g)))
print("Desvio padrao (Raiz quadrada(1/lambda^2)): " + str(np.std(g)))
print("Nota: caso a media e o desvio padrao nap sejam proximos dos valores esperados, correr para uma matriz maior")

Média (1/lambda): 0.13613898125724969
Desvio padrao (Raiz quadrada(1/lambda^2)): 0.19360374533388341
Nota: caso a media e o desvio padrao nap sejam proximos dos valores esperados, correr para uma matriz maior


Slicing de vetores n dimensionais

tambem permite o slicing, visto no notebook "introdução ao Python"

In [ ]:
a = np.array ([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2,:]
c = a[:2, 1:3]
print(a)
print()
print(b)
print()
print(c)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[1 2 3 4]
 [5 6 7 8]]

[[2 3]
 [6 7]]


In [ ]:
e = np.array ([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [ ]:
# Retira a segunda linha para uma matriz unidemensional
l1_d1 = e[1,:]

#Imprime~os valores da segunda linha e respectivo formato
print(l1_d1, l1_d1.shape)

[5 6 7 8] (4,)


In [ ]:
# Retira a segunda linha para uma matriz bidimensional

c1_d2 = e[:, 1:2]
print(c1_d2, c1_d2.shape)

[[ 2]
 [ 6]
 [10]] (3, 1)


Indexação de matrizes/ndarray
A biblioteca NumPy permite seleccionar elementos de uma matriz/ndarray tendo por base outras matrizes e expressoes boleanas

In [ ]:
#Indexação de matrizes utilizando outras matrizes

a = np.array([[1,2], [3,4], [5,6]])
print("Matriz a de 3x2:")
print(a)

Matriz a de 3x2:
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Indexação utilizando uma matriz de posições a mostrar

print(a[[0,1,2], [0,1,0]]) # mostrar os elementos que estao na posição 0,0->1; 1,1->4; 2,0->5

[1 4 5]


In [ ]:
# O exemplo acima pode ser conseguido atraves da indicação de cada um dos elementos

print(np.array([a[0,0], a[1,1], a[2,0]]))

IndexError: index 2 is out of bounds for axis 1 with size 2

In [ ]:
#Ao utilizar uma matriz de elementos  inteiros para indexação podems reutilziar elementos

print(a[[0,0], [1,1]])

[2 2]


In [ ]:
# Alterar os elementos de posições da matriz

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
b = np.array([0,2,0,1])
b

array([0, 2, 0, 1])

In [ ]:
# Seleccionar um elemento de cada linha utilizando os indices em b

print(a[np.arange(4), b])

[ 1  6  7 11]


In [ ]:
#Alterar um elemento de cada linha utilizando os indices em b

a[np.arange(4), b] += 10
print(a)
print(np.arange(4)) 
      

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]
[0 1 2 3]


In [ ]:
#indexação  de matrizes utilizando expressoes boleanas
# utilizado para seleccionar os elementos de uma matriz
#que satisfaçam uma determinada condição

a = np.array([[1,2], [3,4], [5,6]])
bool_idx = (a > 2)
print(bool_idx)
print(a[bool_idx])
print(a[bool_idx==True])
print(a[bool_idx==False])
print(a[a > 2])#####

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
[1 2]
[3 4 5 6]
